---
title: Metric Geometry and Gerrymandering Group
timezone: UTC
collections:
  category_pages:
    title: Categories
    output: true
    permalink: "/:title"
    layout: category
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  works:
    title: Works
    output: false
name: Metric Geometry and Gerrymandering Group
url: https://www.mggg.org/
author: Metric Geometry and Gerrymandering Group
description: A nonpartisan research organization studying applications of geometry
twitter: gerrymandr
logo: "/assets/logo.svg"
google_site_verification: jaL3ii25-g2LejBrllWbH-DmyT7b-vJw8URj-tvq8kE
plugins:
- jekyll-seo-tag
sass:
  sass_dir: _sass
include:
- _redirects
